config/routes.rb
Rails.application.routes.draw do
  resources :tests
  resources :records
  resources :symptoms
  resources :assessments
  resources :patients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/assessment.rb
class Assessment < ApplicationRecord
  belongs_to :patient
  
  enum edema: { none: 0, mild: 1, moderate: 2, severe: 3, extreme: 4 }
  enum uterine_tone: { normal: 0, hypertonic: 1, hypotonic: 2, flaccid: 3 }

  validates :labor_duration, presence: true
  # validates :edema, :uterine_tone, presence: true
end

app/controllers/assessments_controller.rb
class AssessmentsController < ApplicationController
  before_action :set_assessment, only: %i[ show edit update destroy ]

  # GET /assessments or /assessments.json
  def index
    @assessments = Assessment.all
  end

  # GET /assessments/1 or /assessments/1.json
  def show
  end

  # GET /assessments/new
  def new
    @assessment = Assessment.new
  end

  # GET /assessments/1/edit
  def edit
  end

  # POST /assessments or /assessments.json
  def create
    @assessment = Assessment.new(assessment_params)

    respond_to do |format|
      if @assessment.save
        format.html { redirect_to @assessment, notice: "Assessment was successfully created." }
        format.json { render :show, status: :created, location: @assessment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @assessment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assessments/1 or /assessments/1.json
  def update
    respond_to do |format|
      if @assessment.update(assessment_params)
        format.html { redirect_to @assessment, notice: "Assessment was successfully updated." }
        format.json { render :show, status: :ok, location: @assessment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @assessment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assessments/1 or /assessments/1.json
  def destroy
    @assessment.destroy!

    respond_to do |format|
      format.html { redirect_to assessments_path, status: :see_other, notice: "Assessment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assessment
      @assessment = Assessment.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def assessment_params
      params.expect(assessment: [ :patient_id, :edema, :labor_duration, :contraction_pattern, :cervical_dilation, :uterine_tone, :fetal_head_position ])
    end
end

app/helpers/assessments_helper.rb
module AssessmentsHelper
end

app/views/assessments/_assessment.html.erb
<div id="<%= dom_id assessment %>">
  <p>
    <strong>Patient:</strong>
    <%= assessment.patient_id %>
  </p>

  <p>
    <strong>Edema:</strong>
    <%= assessment.edema %>
  </p>

  <p>
    <strong>Labor duration:</strong>
    <%= assessment.labor_duration %>
  </p>

  <p>
    <strong>Contraction pattern:</strong>
    <%= assessment.contraction_pattern %>
  </p>

  <p>
    <strong>Cervical dilation:</strong>
    <%= assessment.cervical_dilation %>
  </p>

  <p>
    <strong>Uterine tone:</strong>
    <%= assessment.uterine_tone %>
  </p>

  <p>
    <strong>Fetal head position:</strong>
    <%= assessment.fetal_head_position %>
  </p>

</div>

app/views/assessments/_form.html.erb
<%= form_with(model: assessment) do |form| %>
  <% if assessment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(assessment.errors.count, "error") %> prohibited this assessment from being saved:</h2>

      <ul>
        <% assessment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :patient_id, style: "display: block" %>
    <%= form.text_field :patient_id %>
  </div>

  <div>
    <%= form.label :edema, style: "display: block" %>
    <%= form.checkbox :edema %>
  </div>

  <div>
    <%= form.label :labor_duration, style: "display: block" %>
    <%= form.number_field :labor_duration %>
  </div>

  <div>
    <%= form.label :contraction_pattern, style: "display: block" %>
    <%= form.text_field :contraction_pattern %>
  </div>

  <div>
    <%= form.label :cervical_dilation, style: "display: block" %>
    <%= form.text_field :cervical_dilation %>
  </div>

  <div>
    <%= form.label :uterine_tone, style: "display: block" %>
    <%= form.text_field :uterine_tone %>
  </div>

  <div>
    <%= form.label :fetal_head_position, style: "display: block" %>
    <%= form.text_field :fetal_head_position %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/assessments/edit.html.erb
<% content_for :title, "Editing assessment" %>

<h1>Editing assessment</h1>

<%= render "form", assessment: @assessment %>

<br>

<div>
  <%= link_to "Show this assessment", @assessment %> |
  <%= link_to "Back to assessments", assessments_path %>
</div>

app/views/assessments/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Assessments" %>

<h1>Assessments</h1>

<div id="assessments">
  <% @assessments.each do |assessment| %>
    <%= render assessment %>
    <p>
      <%= link_to "Show this assessment", assessment %>
    </p>
  <% end %>
</div>

<%= link_to "New assessment", new_assessment_path %>

app/views/assessments/new.html.erb
<% content_for :title, "New assessment" %>

<h1>New assessment</h1>

<%= render "form", assessment: @assessment %>

<br>

<div>
  <%= link_to "Back to assessments", assessments_path %>
</div>

app/views/assessments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @assessment %>

<div>
  <%= link_to "Edit this assessment", edit_assessment_path(@assessment) %> |
  <%= link_to "Back to assessments", assessments_path %>

  <%= button_to "Destroy this assessment", @assessment, method: :delete %>
</div>