config/routes.rb
Rails.application.routes.draw do
  resources :tests
  resources :records
  resources :symptoms
  resources :assessments
  resources :patients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/symptom.rb
class Symptom < ApplicationRecord
  belongs_to :patient

  enum severity: { mild: 0, moderate: 1, severe: 2, critical: 3}

  validates :name, presence: true, uniqueness: { scope: :patient_id }
  validates :severity, presence: true, inclusion: { in: %w[mild moderate severe critical] }
  validates :reported_at, presence: true
end

app/controllers/symptoms_controller.rb
class SymptomsController < ApplicationController
  before_action :set_symptom, only: %i[ show edit update destroy ]

  # GET /symptoms or /symptoms.json
  def index
    @symptoms = Symptom.all
  end

  # GET /symptoms/1 or /symptoms/1.json
  def show
  end

  # GET /symptoms/new
  def new
    @symptom = Symptom.new
  end

  # GET /symptoms/1/edit
  def edit
  end

  # POST /symptoms or /symptoms.json
  def create
    @symptom = Symptom.new(symptom_params)

    respond_to do |format|
      if @symptom.save
        format.html { redirect_to @symptom, notice: "Symptom was successfully created." }
        format.json { render :show, status: :created, location: @symptom }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @symptom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /symptoms/1 or /symptoms/1.json
  def update
    respond_to do |format|
      if @symptom.update(symptom_params)
        format.html { redirect_to @symptom, notice: "Symptom was successfully updated." }
        format.json { render :show, status: :ok, location: @symptom }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @symptom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /symptoms/1 or /symptoms/1.json
  def destroy
    @symptom.destroy!

    respond_to do |format|
      format.html { redirect_to symptoms_path, status: :see_other, notice: "Symptom was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_symptom
      @symptom = Symptom.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def symptom_params
      params.expect(symptom: [ :patient_id, :name, :severity, :description, :reported_at ])
    end
end

app/helpers/symptoms_helper.rb
module SymptomsHelper
end

app/views/symptoms/_form.html.erb
<%= form_with(model: symptom) do |form| %>
  <% if symptom.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(symptom.errors.count, "error") %> prohibited this symptom from being saved:</h2>

      <ul>
        <% symptom.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :patient_id, style: "display: block" %>
    <%= form.text_field :patient_id %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :severity, style: "display: block" %>
    <%= form.number_field :severity %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.textarea :description %>
  </div>

  <div>
    <%= form.label :reported_at, style: "display: block" %>
    <%= form.datetime_field :reported_at %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/symptoms/_symptom.html.erb
<div id="<%= dom_id symptom %>">
  <p>
    <strong>Patient:</strong>
    <%= symptom.patient_id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= symptom.name %>
  </p>

  <p>
    <strong>Severity:</strong>
    <%= symptom.severity %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= symptom.description %>
  </p>

  <p>
    <strong>Reported at:</strong>
    <%= symptom.reported_at %>
  </p>

</div>

app/views/symptoms/edit.html.erb
<% content_for :title, "Editing symptom" %>

<h1>Editing symptom</h1>

<%= render "form", symptom: @symptom %>

<br>

<div>
  <%= link_to "Show this symptom", @symptom %> |
  <%= link_to "Back to symptoms", symptoms_path %>
</div>

app/views/symptoms/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Symptoms" %>

<h1>Symptoms</h1>

<div id="symptoms">
  <% @symptoms.each do |symptom| %>
    <%= render symptom %>
    <p>
      <%= link_to "Show this symptom", symptom %>
    </p>
  <% end %>
</div>

<%= link_to "New symptom", new_symptom_path %>

app/views/symptoms/new.html.erb
<% content_for :title, "New symptom" %>

<h1>New symptom</h1>

<%= render "form", symptom: @symptom %>

<br>

<div>
  <%= link_to "Back to symptoms", symptoms_path %>
</div>

app/views/symptoms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @symptom %>

<div>
  <%= link_to "Edit this symptom", edit_symptom_path(@symptom) %> |
  <%= link_to "Back to symptoms", symptoms_path %>

  <%= button_to "Destroy this symptom", @symptom, method: :delete %>
</div>