config/routes.rb
Rails.application.routes.draw do
  resources :tests
  resources :records
  resources :symptoms
  resources :assessments
  resources :patients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :patient

  validates :heartrate, :blood_pressure_systolic, :blood_pressure_diastolic, :recorded_at, presence: true
  validates :oxygen_saturation, :weight, presence: true
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: %i[ show edit update destroy ]

  # GET /records or /records.json
  def index
    @records = Record.all
  end

  # GET /records/1 or /records/1.json
  def show
  end

  # GET /records/new
  def new
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records or /records.json
  def create
    @record = Record.new(record_params)

    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, notice: "Record was successfully created." }
        format.json { render :show, status: :created, location: @record }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1 or /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to @record, notice: "Record was successfully updated." }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1 or /records/1.json
  def destroy
    @record.destroy!

    respond_to do |format|
      format.html { redirect_to records_path, status: :see_other, notice: "Record was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def record_params
      params.expect(record: [ :patient_id, :heart_rate, :blood_pressure_systolic, :blood_pressure_diastolic, :oxygen_saturation, :weight, :recorded_at ])
    end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_form.html.erb
<%= form_with(model: record) do |form| %>
  <% if record.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
        <% record.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :patient_id, style: "display: block" %>
    <%= form.text_field :patient_id %>
  </div>

  <div>
    <%= form.label :heart_rate, style: "display: block" %>
    <%= form.number_field :heart_rate %>
  </div>

  <div>
    <%= form.label :blood_pressure_systolic, style: "display: block" %>
    <%= form.number_field :blood_pressure_systolic %>
  </div>

  <div>
    <%= form.label :blood_pressure_diastolic, style: "display: block" %>
    <%= form.number_field :blood_pressure_diastolic %>
  </div>

  <div>
    <%= form.label :oxygen_saturation, style: "display: block" %>
    <%= form.text_field :oxygen_saturation %>
  </div>

  <div>
    <%= form.label :weight, style: "display: block" %>
    <%= form.text_field :weight %>
  </div>

  <div>
    <%= form.label :recorded_at, style: "display: block" %>
    <%= form.datetime_field :recorded_at %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/records/_record.html.erb
<div id="<%= dom_id record %>">
  <p>
    <strong>Patient:</strong>
    <%= record.patient_id %>
  </p>

  <p>
    <strong>Heart rate:</strong>
    <%= record.heart_rate %>
  </p>

  <p>
    <strong>Blood pressure systolic:</strong>
    <%= record.blood_pressure_systolic %>
  </p>

  <p>
    <strong>Blood pressure diastolic:</strong>
    <%= record.blood_pressure_diastolic %>
  </p>

  <p>
    <strong>Oxygen saturation:</strong>
    <%= record.oxygen_saturation %>
  </p>

  <p>
    <strong>Weight:</strong>
    <%= record.weight %>
  </p>

  <p>
    <strong>Recorded at:</strong>
    <%= record.recorded_at %>
  </p>

</div>

app/views/records/edit.html.erb
<% content_for :title, "Editing record" %>

<h1>Editing record</h1>

<%= render "form", record: @record %>

<br>

<div>
  <%= link_to "Show this record", @record %> |
  <%= link_to "Back to records", records_path %>
</div>

app/views/records/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Records" %>

<h1>Records</h1>

<div id="records">
  <% @records.each do |record| %>
    <%= render record %>
    <p>
      <%= link_to "Show this record", record %>
    </p>
  <% end %>
</div>

<%= link_to "New record", new_record_path %>

app/views/records/new.html.erb
<% content_for :title, "New record" %>

<h1>New record</h1>

<%= render "form", record: @record %>

<br>

<div>
  <%= link_to "Back to records", records_path %>
</div>

app/views/records/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @record %>

<div>
  <%= link_to "Edit this record", edit_record_path(@record) %> |
  <%= link_to "Back to records", records_path %>

  <%= button_to "Destroy this record", @record, method: :delete %>
</div>