config/routes.rb
Rails.application.routes.draw do
  resources :tests
  resources :records
  resources :symptoms
  resources :assessments
  resources :patients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/patient.rb
class Patient < ApplicationRecord
    has_many :assessments, dependent: :destroy
    has_many :symptoms, dependent: :destroy
    has_many :records, dependent: :destroy
    has_many :tests, dependent: :destroy
  
    validates :first_name, :last_name, presence: true
    validates :dob, presence: true
  end
  

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: %i[ show edit update destroy ]

  # GET /patients or /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1 or /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients or /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: "Patient was successfully created." }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1 or /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: "Patient was successfully updated." }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1 or /patients/1.json
  def destroy
    @patient.destroy!

    respond_to do |format|
      format.html { redirect_to patients_path, status: :see_other, notice: "Patient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def patient_params
      params.expect(patient: [ :first_name, :last_name, :dob, :medical_history ])
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_with(model: patient) do |form| %>
  <% if patient.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
        <% patient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :dob, style: "display: block" %>
    <%= form.date_field :dob %>
  </div>

  <div>
    <%= form.label :medical_history, style: "display: block" %>
    <%= form.textarea :medical_history %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/patients/_patient.html.erb
<div id="<%= dom_id patient %>">
  <p>
    <strong>First name:</strong>
    <%= patient.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= patient.last_name %>
  </p>

  <p>
    <strong>Dob:</strong>
    <%= patient.dob %>
  </p>

  <p>
    <strong>Medical history:</strong>
    <%= patient.medical_history %>
  </p>

</div>

app/views/patients/edit.html.erb
<% content_for :title, "Editing patient" %>

<h1>Editing patient</h1>

<%= render "form", patient: @patient %>

<br>

<div>
  <%= link_to "Show this patient", @patient %> |
  <%= link_to "Back to patients", patients_path %>
</div>

app/views/patients/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Patients" %>

<h1>Patients</h1>

<div id="patients">
  <% @patients.each do |patient| %>
    <%= render patient %>
    <p>
      <%= link_to "Show this patient", patient %>
    </p>
  <% end %>
</div>

<%= link_to "New patient", new_patient_path %>

app/views/patients/new.html.erb
<% content_for :title, "New patient" %>

<h1>New patient</h1>

<%= render "form", patient: @patient %>

<br>

<div>
  <%= link_to "Back to patients", patients_path %>
</div>

app/views/patients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @patient %>

<div>
  <%= link_to "Edit this patient", edit_patient_path(@patient) %> |
  <%= link_to "Back to patients", patients_path %>

  <%= button_to "Destroy this patient", @patient, method: :delete %>
</div>